### PR TITLE
Fix import path for bitcask

### PR DESCRIPTION
**Pull request by prologic**
Project has moved to [git.mills.io/prologic/bitcask](https://git.mills.io/prologic/bitcask).

For details on why see: https://github.com/prologic

Thank you! 🙇

### CODE REVIEW

**Comment by donatj** [comment]
For what it's worth from adude in the peanut gallery here, I think it's silly to move off of GitHub.

You're limiting your potential for open source contributions, visibiltiy and userbase overall.

My 2¢, if you're just looking to protect yourself from GitHub making bad moves you'd be better off just setting up a vanity paths https://sagikazarmark.hu/blog/vanity-import-paths-in-go/

For instance, Rob Pike's Ivy lives here: https://github.com/robpike/ivy

But it has the path robpike.io/ivy

**Comment by prologic** [comment]
> For what it's worth from a dude in the peanut gallery here, I think it's silly to move off of GitHub.
> 
> You're limiting your potential for open source contributions, visibility and userbase overall.
> 
> My 2¢, if you're just looking to protect yourself from GitHub making bad moves you'd be better off just setting up a vanity paths https://sagikazarmark.hu/blog/vanity-import-paths-in-go/
> 
> For instance, Rob Pike's Ivy lives here: https://github.com/robpike/ivy
> 
> But it has the path robpike.io/ivy

Yeah you're right. I _will_ loose some visibility, contributions and usebase. I know. I get that. But what M$/Github have done is IHMO inexcusable.

That being said, I've taken every effort to make it as easy and painless to continue to contribute and collaborate with me and others at [git.mills.io](https://git.mills.io) configured with Github OAuth enabled.

I will also setup a vanity server and paths for many of my more widely used Go libraries soon I promise! 🤗 it'll likely end up being like:

```#!sh
go get go.mills.io/bitcask
```

(_For example_)

Thanks for your understanding!

**Comment by donatj** [comment]
> But what M$/Github have done is IHMO inexcusable.

Namely?

**Comment by prologic** [comment]
> > But what M$/Github have done is IHMO inexcusable.
> 
> Namely?
> 
> > For details on why see: https://github.com/prologic
> 
> There’s nothing there on why

Sorry my bad, if you followed the trail you'd end up at several blog posts I wrote:

- https://twtxt.net/blog/prologic/2021/07/11/why-i-no-longer-trust-github
- https://www.prologic.blog/2021/07/11/why-i-no.html

I'm not the only one mate 😉

**Comment by donatj** [comment]
Seems like an overreaction to your code being used to weight some neurons in an AI imho.

If I as a human being read the code of bitcask, and it influenced the way I write code moving forward, should I have to cite it in all my future endeavors? I have been weighting my neurons for 20 years, I have probably tens of thousands of repos to cite for every line of code in that case.

You do you, sir, but I think you’re just being a little bit of a luddite.

**Comment by prologic** [comment]
That is your opinion ☺️ I have my own 😁

And you're misconstruing my stance a bit too far my friend 👌

**Pull request merged**
